export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_FULLFILLED = "SIGNIN_FULLFILLED";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const SIGNUP_REQUESTED = "SIGNUP_REQUESTED";
export const SIGNUP_FULLFILLED = "SIGNUP_FULLFILLED";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SENDOTP_REQUESTED = "SENDOTP_REQUESTED";
export const SENDOTP_FULLFILLED = "SENDOTP_FULLFILLED";
export const SENDOTP_FAILED = "SENDOTP_FAILED";

export const RESETPASSWORD_REQUESTED = "RESETPASSWORD_REQUESTED";
export const RESETPASSWORD_FULLFILLED = "RESETPASSWORD_FULLFILLED";
export const RESETPASSWORD_FAILED = "RESETPASSWORD_FAILED";

export const SIGNOUT = "SIGNOUT";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE"