# This workflow will build a package using maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD with Maven and Docker

on:
  push:
    branches: [main]

jobs:
  build-react:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm install --force
      # - run: CI='' npm run build --if-present

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "rajeshmylsamy/books-web"
          TAG_NAME: "v1"
          LATEST: "true"
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: "http://164.52.197.201:8085/hooks/redeploy-books-web"
